Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.132:39705'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.132:56300'
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:   tcp://10.148.0.132:33916
distributed.worker - INFO -          Listening to:   tcp://10.148.0.132:33916
distributed.worker - INFO -              nanny at:         10.148.0.132:39705
distributed.worker - INFO -              bokeh at:          10.148.0.132:8789
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:   tcp://10.148.0.132:54459
distributed.worker - INFO - Waiting to connect to:     tcp://10.148.1.2:35178
distributed.worker - INFO -          Listening to:   tcp://10.148.0.132:54459
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -              nanny at:         10.148.0.132:56300
distributed.worker - INFO -              bokeh at:         10.148.0.132:58704
distributed.worker - INFO - Waiting to connect to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.1346232.datarmor0/worker-83sgxpbg
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.1346232.datarmor0/worker-lzr3bqqr
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:     tcp://10.148.1.2:35178
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.core - INFO - Event loop was unresponsive in Worker for 3.64s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 3.63s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 23.44s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.core - INFO - Event loop was unresponsive in Worker for 23.36s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/dask/array/chunk.py:228: ComplexWarning: Casting complex values to real discards the imaginary part
  return x.astype(astype_dtype, **kwargs)
distributed.core - INFO - Event loop was unresponsive in Worker for 4.49s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
distributed.worker - INFO - Can't find dependencies for key ('detrend-multiply-fftn-ff47af91f0a9399d975c9d8173d97c8c', 392, 1, 0)
distributed.worker - INFO - Dependent not found: ('where-df72cf21e168d64356411fd221dff700', 392, 1, 0) 0 .  Asking scheduler
distributed.worker - INFO - Can't find dependencies for key ('detrend-multiply-fftn-ff47af91f0a9399d975c9d8173d97c8c', 116, 4, 0)
distributed.worker - INFO - Dependent not found: ('where-df72cf21e168d64356411fd221dff700', 116, 4, 0) 0 .  Asking scheduler
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/dask/array/chunk.py:228: ComplexWarning: Casting complex values to real discards the imaginary part
  return x.astype(astype_dtype, **kwargs)
distributed.utils_perf - INFO - full garbage collection released 10.60 MB from 65079 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 23.61 MB from 129754 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 99.45 MB from 0 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 10.16 MB from 64850 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 10.94 MB from 64853 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 94.72 MB from 65056 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 66.76 MB from 389432 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 10.53 MB from 64885 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 26.03 MB from 129722 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 41.88 MB from 259694 reference cycles (threshold: 10.00 MB)
distributed.utils_perf - INFO - full garbage collection released 11.38 MB from 64895 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Stopping worker at tcp://10.148.0.132:33916
distributed.worker - INFO - Stopping worker at tcp://10.148.0.132:54459
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.132:56300'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.132:39705'
distributed.dask_worker - INFO - End worker
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
