Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.218:33494'
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.148.0.218:35345'
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:   tcp://10.148.0.218:56944
distributed.worker - INFO -          Listening to:   tcp://10.148.0.218:56944
distributed.worker - INFO -              nanny at:         10.148.0.218:35345
distributed.worker - INFO -              bokeh at:          10.148.0.218:8789
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.2935111.datarmor0/worker-0fx25wxr
distributed.worker - INFO - -------------------------------------------------
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
distributed.worker - INFO -       Start worker at:   tcp://10.148.0.218:49988
distributed.worker - INFO -          Listening to:   tcp://10.148.0.218:49988
distributed.worker - INFO -              nanny at:         10.148.0.218:33494
distributed.worker - INFO -              bokeh at:         10.148.0.218:56609
distributed.worker - INFO - Waiting to connect to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          4
distributed.worker - INFO -         Registered to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -                Memory:                   50.00 GB
distributed.worker - INFO -       Local Directory: /dev/shm/pbs.2935111.datarmor0/worker-rgnqy0un
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.worker - INFO -         Registered to:    tcp://10.148.1.21:49173
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
distributed.utils_perf - INFO - full garbage collection released 373.07 MB from 276 reference cycles (threshold: 10.00 MB)
distributed.worker - INFO - Can't find dependencies for key ('add-157733b11a35e24966f4815b66d9f7ae', 0, 591, 0, 0)
distributed.worker - INFO - Dependent not found: ('rechunk-merge-64cf0f93e6f50d76bbd1998606c32ffe', 0, 591, 0, 0) 0 .  Asking scheduler
distributed.worker - INFO - Stopping worker at tcp://10.148.0.218:56944
distributed.worker - INFO - Stopping worker at tcp://10.148.0.218:49988
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - -------------------------------------------------
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.218:33494'
distributed.nanny - INFO - Closing Nanny at 'tcp://10.148.0.218:35345'
distributed.dask_worker - INFO - End worker
/home1/datahome/xyu/.miniconda3/envs/equinox/lib/python3.6/site-packages/distributed/utils.py:128: RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1': [Errno 101] Network is unreachable
  % (host, default, e), RuntimeWarning)
